<?php

namespace App\Models;

use CodeIgniter\Model;

class Room extends Model
{
    /*This is protected variables for Room Model*/
    protected $roomNo = 'roomNo';
    protected $roomName = 'roomName';
    protected $capacity = 'capacity';
    protected $status = 'status';

    /*6 Sample data for Room Model*/
    protected $data =
        [
        'Room1' => ['roomNo' => '1', 'roomName' => '6953', 'capacity' => '04', 'status' => 'booked'],
        'Room2' => ['roomNo' => '2', 'roomName' => '7001', 'capacity' => '10', 'status' => 'available'],
        'Room3' => ['roomNo' => '3', 'roomName' => '6891', 'capacity' => '11', 'status' => 'booked'],
        'Room4' => ['roomNo' => '4', 'roomName' => '1234', 'capacity' => '07', 'status' => 'available'],
        'Room5' => ['roomNo' => '5', 'roomName' => '4615', 'capacity' => '05', 'status' => 'booked'],
        'Room6' => ['roomNo' => '6', 'roomName' => '1122', 'capacity' => '15', 'status' => 'available']
    ];

    /*This function find a specific room based on roomNo*/
    public function find($roomNo = null)
    {
        return $this->data[$roomNo];
    }

    /*This function find all room*/
    public function findAll(int $limit = 0, int $offset = 0)
    {
        return $this->data; // TODO: Change the autogenerated stub
    }

}
